"""
AdaptIQ AI Engine — Pydantic Data Models

All data contracts used across the enterprise learning pipeline
and the original research pipeline.
"""

from pydantic import BaseModel, Field
from typing import Optional


# ─── Enterprise Learning Request Models ─────────────────────────────

class LearningPlanRequest(BaseModel):
    """Request for a full learning plan (Curator + Study Plan agents)."""
    job_id: str = Field(..., description="UUID of the learning job")
    role: str = Field(..., description="Learner's job role (e.g., 'Cloud Engineer')")
    goal: str = Field(..., description="Learning goal (e.g., 'Get AZ-204 certified')")
    employee_id: str = Field(default="EMP-1001", description="Work IQ / Fabric IQ employee ID")
    experience_level: str = Field(default="intermediate", description="beginner/intermediate/advanced")
    weeks_available: int = Field(default=6, description="Target weeks to complete certification")


class AssessmentRequest(BaseModel):
    """Request for grounded assessment questions."""
    job_id: str = Field(..., description="UUID of the assessment job")
    target_certification: str = Field(..., description="Target cert ID (e.g., 'AZ-204')")
    employee_id: str = Field(default="EMP-1001", description="Fabric IQ employee ID")


# ─── Inbound Request ────────────────────────────────────────────────

class SynthesizeRequest(BaseModel):
    """Payload from Spring Boot gateway."""
    job_id: str = Field(..., description="UUID of the research job")
    query: str = Field(..., description="The user's research query")


# ─── Internal Pipeline Models ───────────────────────────────────────

class SubQuery(BaseModel):
    """A targeted sub-query generated by the Planner."""
    question: str = Field(..., description="The sub-query text")
    rationale: str = Field(default="", description="Why this sub-query matters")


class RetrievedDocument(BaseModel):
    """A document/fact retrieved from Foundry IQ."""
    source_url: str = Field(..., description="URL of the source")
    snippet: str = Field(..., description="Relevant text excerpt")
    foundry_id: str = Field(default="", description="Foundry IQ document ID")
    relevance_score: float = Field(default=0.0, description="0.0-1.0 relevance")


class DraftReport(BaseModel):
    """Intermediate draft produced by the Synthesizer."""
    executive_summary: str = Field(..., description="High-level summary")
    detailed_content: str = Field(..., description="Full detailed analysis")
    citations_used: list[RetrievedDocument] = Field(
        default_factory=list, description="Documents cited in the report"
    )


class CritiqueResult(BaseModel):
    """Output of the Reflexion critic."""
    passed: bool = Field(..., description="Whether the draft meets quality bar")
    confidence_score: float = Field(
        ..., description="Confidence in the report (0-100)"
    )
    gaps: list[str] = Field(
        default_factory=list, description="Identified gaps or issues"
    )
    suggested_queries: list[str] = Field(
        default_factory=list, description="Follow-up queries to fill gaps"
    )
    reasoning: str = Field(default="", description="Critique reasoning")


# ─── Trace / Telemetry ──────────────────────────────────────────────

class TraceEntry(BaseModel):
    """A single action log entry for debugging the Reflexion loop."""
    iteration_number: int = Field(alias="iterationNumber")
    action_taken: str = Field(alias="actionTaken") # e.g., PLAN_QUERIES, FOUNDRY_SEARCH, SYNTHESIZE, SELF_CRITIQUE
    action_input: str = Field(alias="actionInput")
    observation: str

    model_config = {"populate_by_name": True}


# ─── Outbound Callback ──────────────────────────────────────────────

class CompletionPayload(BaseModel):
    """Payload sent back to Spring Boot on job completion."""
    executive_summary: str = Field(alias="executiveSummary")
    detailed_content: str = Field(alias="detailedContent")
    confidence_score: float = Field(alias="confidenceScore")
    citations: str  # JSON-serialized list of citation objects
    iteration_count: int = Field(alias="iterationCount")
    processing_time_ms: int = Field(alias="processingTimeMs")
    traces: list[TraceEntry] = Field(default_factory=list)

    model_config = {"populate_by_name": True}


class FailurePayload(BaseModel):
    """Payload sent back to Spring Boot on job failure."""
    error: str
